export const REFRESH_POSITIONS = "REFRESH_POSITIONS"
export const EDIT_FORM = "EDIT_FORM"
export const REVERT_FORM_EDITS = "REVERT_FORM_EDITS"
export const COMMIT_FORM_EDITS = "COMMIT_FORM_EDITS"
export const ADD_DELETE_POSITION = "ADD_DELETE_POSITION"
export const ADD_DELETE_BASE_SALARY = "ADD_DELETE_BASE_SALARY"

export type PositionsEditorType = "REFRESH_POSITIONS" | "EDIT_FORM" | "REVERT_FORM_EDITS" | "COMMIT_FORM_EDITS" | "ADD_DELETE_POSITION" | "ADD_DELETE_BASE_SALARY"