export const REFRESH_BENEFITS = "REFRESH_BENEFITS"
export const EDIT_FORM = "EDIT_FORM"
export const REVERT_FORM_EDITS = "REVERT_FORM_EDITS"
export const COMMIT_FORM_EDITS = "COMMIT_FORM_EDITS"
export const ADD_DELETE_BENEFIT = "ADD_DELETE_BENEFIT"
export const ADD_DELETE_BENEFIT_OPTION = "ADD_DELETE_BENEFIT_OPTION"

export type BenefitsEditorType = "REFRESH_BENEFITS" | "EDIT_FORM" | "REVERT_FORM_EDITS" | "COMMIT_FORM_EDITS" | "ADD_DELETE_BENEFIT" | "ADD_DELETE_BENEFIT_OPTION"